export const COUNTRIES = [
    'Afganistan',
    'Albania',
    'Algieria',
    'Andora',
    'Angola',
    'Anguilla',
    'Antigua i Barbuda',
    'Arabia Saudyjska',
    'Argentyna',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbejdżan',
    'Bahamy',
    'Bahrajn',
    'Bangladesz',
    'Barbados',
    'Belgia',
    'Belize',
    'Benin',
    'Bermudy',
    'Bhutan',
    'Białoruś',
    'Birma',
    'Boliwia',
    'Bonaire, Sint Eustatius i Saba',
    'Bośnia i Hercegowina',
    'Botswana',
    'Brazylia',
    'Brunei Darussalam',
    'Brytyjskie Wyspy Dziewicze',
    'Bułgaria',
    'Burkina Faso',
    'Burundi',
    'Chile',
    'Chiny',
    'Chorwacja',
    'Curaçao',
    'Cypr',
    'Czad',
    'Czarnogóra',
    'Czechy',
    'Dania',
    'Demokratyczna Republika Konga',
    'Dominika',
    'Dżibuti',
    'Egipt',
    'Ekwador',
    'Erytrea',
    'Estonia',
    'Etiopia',
    'Federalne Stany Mikronezji',
    'Fidżi',
    'Filipiny',
    'Finlandia',
    'Francja',
    'Gabon',
    'Gambia',
    'Ghana',
    'Gibraltar',
    'Grecja',
    'Grenada',
    'Gruzja',
    'Gujana',
    'Gujana Francuska',
    'Gwadelupa',
    'Gwatemala',
    'Gwinea',
    'Gwinea Bissau',
    'Gwinea Równikowa',
    'Haiti',
    'Hiszpania',
    'Holandia',
    'Honduras',
    'Hongkong',
    'Indie',
    'Indonezja',
    'Irak',
    'Iran',
    'Irlandia',
    'Irlandia Północna',
    'Islandia',
    'Izrael',
    'Jamajka',
    'Japonia',
    'Jemen',
    'Jordania',
    'Kajmany',
    'Kambodża',
    'Kamerun',
    'Kanada',
    'Katar',
    'Kazachstan',
    'Kenia',
    'Kirgistan',
    'Kiribati',
    'Kolumbia',
    'Komory',
    'Kongo',
    'Korea Północna',
    'Korea Południowa',
    'Kosowo',
    'Kostaryka',
    'Kuba',
    'Kuwejt',
    'Laos',
    'Lesotho',
    'Liban',
    'Liberia',
    'Libia',
    'Liechtenstein',
    'Litwa',
    'Łotwa',
    'Luksemburg',
    'Macedonia',
    'Madagaskar',
    'Malawi',
    'Malediwy',
    'Malezja',
    'Mali',
    'Malta',
    'Maroko',
    'Martynika',
    'Mauretania',
    'Mauritius',
    'Meksyk',
    'Mołdawia',
    'Monako',
    'Mongolia',
    'Mozambik',
    'Namibia',
    'Nauru',
    'Nepal',
    'Niemcy',
    'Niger',
    'Nigeria',
    'Nikaragua',
    'Norwegia',
    'Nowa Kaledonia',
    'Nowa Zelandia',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua Nowa Gwinea',
    'Paragwaj',
    'Peru',
    'Polinezja Francuska',
    'Polska',
    'Portoryko',
    'Portugalia',
    'Republika Dominikańska',
    'Republika Południowej Afryki',
    'Republika Środkowoafrykańska',
    'Republika Zielonego Przylądka',
    'Reunion',
    'Rosja',
    'Rumunia',
    'Rwanda',
    'Saint Kitts i Nevis',
    'Saint Lucia',
    'Saint Vincent i Grenadyny',
    'Salwador',
    'Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Seszele',
    'Sierra Leone',
    'Singapur',
    'Słowacja',
    'Słowenia',
    'Somalia',
    'Sri Lanka',
    'Stany Zjednoczone',
    'Suazi',
    'Sudan',
    'Surinam',
    'Syria',
    'Szwajcaria',
    'Szwecja',
    'Tadżykistan',
    'Tajlandia',
    'Tajwan',
    'Tanzania',
    'Timor Wschodni',
    'Togo',
    'Tonga',
    'Trynidad i Tobago',
    'Tunezja',
    'Turcja',
    'Turkmenistan',
    'Turks i Caicos',
    'Tuvalu',
    'Uganda',
    'Ukraina',
    'Urugwaj',
    'Uzbekistan',
    'Vanuatu',
    'Watykan',
    'Węgry',
    'Wenezuela',
    'Wielka Brytania',
    'Wietnam',
    'Włochy',
    'Wybrzeże Kości Słoniowej',
    'Wyspa Guernsey',
    'Wyspa Jersey',
    'Wyspa Man',
    'Wyspa Świętej Heleny',
    'Wyspy Kanaryjskie',
    'Wyspy Marshalla',
    'Wyspy Owcze',
    'Wyspy Salomona',
    'Wyspy Świętego Tomasza i Książęca',
    'Zambia',
    'Zimbabwe',
    'Zj. Emiraty Arabskie',
];
