/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "sanctum.csrf-cookie": [],
    "api.": [],
    "api.profile.update-profile": [],
    "api.profile.update-password": [],
    "api.profile.delete-account": [],
    "api.invoices.index": [],
    "api.invoices.store": [],
    "api.invoices.update": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "api.invoices.destroy": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "api.invoices.status-distribution-by-year": [],
    "api.invoices.status-monthly-series": [],
    "api.invoices.send-email": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "api.contractors.index": [],
    "api.contractors.store": [],
    "api.contractors.update": [
        {
            "name": "contractor",
            "required": true,
            "binding": "id"
        }
    ],
    "api.contractors.destroy": [
        {
            "name": "contractor",
            "required": true,
            "binding": "id"
        }
    ],
    "api.products.index": [],
    "api.products.store": [],
    "api.products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "api.products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "api.premium-account.payments": [],
    "root": [],
    "dashboard": [],
    "invoices": [],
    "invoices.create": [],
    "invoices.show": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "invoices.edit": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "invoices.pdf-preview": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "invoices.pdf-download": [
        {
            "name": "invoice",
            "required": true,
            "binding": "id"
        }
    ],
    "settings": [],
    "contractors": [],
    "products": [],
    "analytics": [],
    "premium-account": [],
    "premium-account.buy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
