export enum PaymentMethod {
    BANK_TRANSFER = 'PrzelewDodaj rachunek bankowy',
    CASH = 'Gotówka',
    CARD = 'Karta płatnicza',
    BARTER = 'Barter',
    CHEQUE = 'Czek',
    COD = 'Za pobraniem',
    OTHER = 'Inny',
    COMPENSATION = 'Kompensata',
    LETTER_OF_CREDIT = 'AkredytywaDodaj rachunek bankowy',
    PAYPAL = 'PayPal',
    PAYU = 'PayU',
    PROMISSORY_NOTE = 'Weksel',
    PREPAYMENT = 'Przedpłata',
    INSTALLMENT_SALE = 'Sprzedaż ratalna',
    TPAY = 'Tpay',
    PRZELEWY24 = 'Przelewy24',
    DOTPAY = 'Dotpay',
}
